# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]  # Ensure the branch is correct (you may want to use "main" if that's your default branch)

jobs:
  build:
    runs-on: self-hosted  # This indicates that you're using a self-hosted runner. Make sure your runner is properly set up.

    strategy:
      matrix:
        node-version: [20.x]  # Adjust if you need multiple Node.js versions

    steps:
    - uses: actions/checkout@v4  # Checkout the code

    - name: Use Node.js ${{ matrix.node-version }}  # Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies  # Run npm install instead of npm ci if the lock file is missing or needs regeneration
      run: npm install

    - name: Create .env file with secrets  # Write secrets to the .env file
      run: |
        touch .env  # Create the .env file if it doesn't exist
        echo "${{secrets.PROD_ENV_FILE}}" > .env  # Store secret in .env from GitHub secrets
        
    - name: Restart PM2 application
      run: pm2 restart quivlentnodeserver 

